import type { Metadata } from "next";

// Components
import { Navbar } from "../components/Navbar";
import { Sidebar } from "../components/Sidebar";
import Footer from "../components/Footer";

// Fonts
import { Poppins, Inter, Roboto_Mono, Fira_Code } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

const firaCode = Fira_Code({
  subsets: ["latin"],
  variable: "--font-fira-code",
});

export const metadata: Metadata = {
  title: "Maximiliano Frias Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${poppins.variable} ${inter.variable} ${robotoMono.variable} ${firaCode.variable} font-sans min-h-screen flex flex-col`}
      >
        <div className="">
          <Sidebar />
          <Navbar />
          <main className="w-full">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
