// import type { Metadata } from "next";

// // Components
// import { Navbar } from "../components/Navbar";
// import { Sidebar } from "../components/Sidebar";

// // Fonts
// import { Poppins, Inter, Roboto_Mono, Fira_Code } from "next/font/google";
// import "./globals.css";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   variable: "--font-poppins",
// });

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
// });

// const robotoMono = Roboto_Mono({
//   subsets: ["latin"],
//   variable: "--font-roboto-mono",
// });

// const firaCode = Fira_Code({
//   subsets: ["latin"],
//   variable: "--font-fira-code",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         <link
//           href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
//           rel="stylesheet"
//         ></link>
//       </head>
//       <body
//         className={`${poppins.variable} ${inter.variable} ${robotoMono.variable} ${firaCode.variable} font-sans`}
//       >
//         <div className="flex">
//           <Sidebar />
//           <div className="ml-16 w-full">
//             {children}
//             <Navbar />
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";

// Components
import { Navbar } from "../components/Navbar";
import { Sidebar } from "../components/Sidebar";

// Fonts
import { Poppins, Inter, Roboto_Mono, Fira_Code } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

const firaCode = Fira_Code({
  subsets: ["latin"],
  variable: "--font-fira-code",
});

export const metadata: Metadata = {
  title: "Maximiliano Frias Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${poppins.variable} ${inter.variable} ${robotoMono.variable} ${firaCode.variable} font-sans`}
      >
        <div className="flex">
          <Sidebar />
          <div className="ml-16 w-full">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
